/**
 * Application Constants and Enums
 */

export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  MECHANIC: 'MECHANIC',
});

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
});

export const MECHANIC_VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

export const MECHANIC_AVAILABILITY_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  OFFLINE: 'OFFLINE',
  BREAK: 'BREAK',
});

export const MECHANIC_WORK_STATUS = Object.freeze({
  IDLE: 'IDLE',
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE: 'EN_ROUTE',
  ON_JOB: 'ON_JOB',
});

export const BOOKING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  ON_THE_WAY: 'ON_THE_WAY',
  ARRIVED: 'ARRIVED',
  INSPECTION: 'INSPECTION',
  QUOTE_PENDING: 'QUOTE_PENDING',
  QUOTE_APPROVED: 'QUOTE_APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  PAID: 'PAID',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
});

export const BOOKING_TYPES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  EMERGENCY_ROADSIDE: 'EMERGENCY_ROADSIDE',
  DOORSTEP_SERVICE: 'DOORSTEP_SERVICE',
});

export const DISPATCH_STATUS = Object.freeze({
  PENDING: 'PENDING',
  OFFERED: 'OFFERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  REASSIGNED: 'REASSIGNED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  COMPLETED: 'COMPLETED',
});

export const PAYMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED',
});

export const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
});

export const VEHICLE_TYPES = Object.freeze({
  TWO_WHEELER: 'TWO_WHEELER',
  FOUR_WHEELER: 'FOUR_WHEELER',
  COMMERCIAL: 'COMMERCIAL',
});

export const SERVICE_CATEGORIES = Object.freeze({
  PERIODIC_MAINTENANCE: 'PERIODIC_MAINTENANCE',
  BRAKES: 'BRAKES',
  TYRES: 'TYRES',
  BATTERY: 'BATTERY',
  AC_SERVICE: 'AC_SERVICE',
  ENGINE_CLUTCH: 'ENGINE_CLUTCH',
  ELECTRICAL_LIGHTS: 'ELECTRICAL_LIGHTS',
  DETAILING: 'DETAILING',
  EMERGENCY_REPAIR: 'EMERGENCY_REPAIR',
});

export const PART_CATEGORIES = Object.freeze({
  ENGINE: 'ENGINE',
  BRAKES: 'BRAKES',
  SUSPENSION: 'SUSPENSION',
  ELECTRICAL: 'ELECTRICAL',
  BODY: 'BODY',
  FILTERS: 'FILTERS',
  OILS_LUBRICANTS: 'OILS_LUBRICANTS',
  TYRES_WHEELS: 'TYRES_WHEELS',
  ACCESSORIES: 'ACCESSORIES',
});
